version: '3.8'

services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 10s
        timeout: 5s
        retries: 5
  weatherapp:
    build: ./
    command:  ./weatherApp
    ports:
      - "8071:8071"
    depends_on:
      db:
       condition: service_healthy
    environment:
      -DB_PASSWORD: "password"

